### ISSUE TITLE
ARP Request time out

### ISSUE THREAD

**Issue by awaisather** [mtcp-stack/mtcp#231]
Hi,
I am running epserver and epwget for single-process, multi-threaded usage and every time I am getting arp request time out error. 
[  ARPTimer: 323] [CPU 0] ARP request for 10.10.1.30 timed out.

I have used following Intel NIC's separately but still error remains same:

I350 Gigabit Network Connection 152
Ethernet Controller X710 for 10GbE SFP+ 1572

Does anyone know about this issue?

**Comment by ajamshed** [comment]
Can you please share the following details:

1. `epserver.conf` contents,
2. `epwget.conf` contents,
3. IP addresses of the two NICs.

Please make sure that NetworkManager is turned off.

**Comment by ranawais** [comment]
Thanks for your response,our problem is solved, we were trying our setup using router gateway instead of using lan.using lan solved our problems.

**Comment by TobeyJin** [comment]
I’m getting the same problem and I have turned off the NetworkManager.  How did you solve it?

**Comment by a-jamshed** [comment]
Please check if you can run the test successfully with static ARP table entries correctly first. Please see the format of how you can set ARP entries by looking at `config/sample_arp.conf`. The file should be copied to `apps/example/config/` subdirectory. If, after setting the files (on both sides), you still see the same errors, then something else may be wrong. In that case, please share the contents of the following files: `epserver.conf`, `epwget.conf` and the `ifconfig dpdk0` output of both machines.
